# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
autoload -Uz compinit && compinit

alias c="clear"
alias gs="git status"
alias gd="git diff"
alias gp="git pull"
alias gb="git branch"
alias gl="git log"

# https://scriptingosx.com/2019/07/moving-to-zsh-06-customizing-the-zsh-prompt/
# https://git-scm.com/book/en/v2/Appendix-A%3A-Git-in-Other-Environments-Git-in-Zsh
# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Version-Control-Information
autoload -Uz vcs_info
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst
zstyle ':vcs_info:git:*' formats '%F{green}(%b)%f'
zstyle ':vcs_info:*' enable git
PROMPT="%F{magenta}%n%f%F{cyan}@%f%F{yellow}%m%f %F{cyan}%1~%f %F{green}\$vcs_info_msg_0_%f %# "

# Oh My Zsh https://github.com/ohmyzsh/ohmyzsh
#export ZSH=$HOME/.oh-my-zsh
#ZSH_THEME="pygmalion"
#plugins=(git)
#source $ZSH/oh-my-zsh.sh